# Display the VPC ID generated by the VPC module
output "final_vpc_id" {
  description = "The ID of the VPC created by the module"
  value       = module.my_vpc.vpc_id
}

# Display the Public Subnet ID
output "final_public_subnet_id" {
  description = "The ID of the Public Subnet created by the module"
  value       = module.my_vpc.public_subnet_id
}

# Display the Private Subnet ID
output "final_private_subnet_id" {
  description = "The ID of the Private Subnet created by the module"
  value       = module.my_vpc.private_subnet_id
}
